name: CI

on: [pull_request]

env:
  BUNDLE_PATH: vendor/bundle

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sdk:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v4
      - name: Build SDK
        run: make build-xcframeworks

  build-docs:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v4
      - name: Build Docs
        run: make build-docs

  run-tests:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v4
      - name: Install xcodegen
        run: brew install xcodegen
      - name: Test
        run: make test build-samples

  pod-lib-lint:
    runs-on: macos-13-xl
    steps:
      - uses: actions/checkout@v4
      - name: Pod lint
        run: make pod-lint
